# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Assembly-Info-NetCore@3
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/*.csproj'
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    PackageRequireLicenseAcceptance: 'false'
    PackageId: 'SmartPixl.Sdk'
    Authors: 'Kevin Becker'
    PackageLicenseExpression: 'MIT'
    VersionNumber: '$(nugVersion)'
    FileVersionNumber: '$(nugVersion)'
    InformationalVersion: '$(nugVersion)'
    PackageVersion: '$(nugVersion)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.org'